package project.lab6;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import static java.util.Objects.nonNull;
import javax.swing.JTextArea;
import project.lab6.element.Element;

// абстрактний клас для загальних змінних і методів
public abstract class AbstractBasePanel extends javax.swing.JPanel {

    protected boolean draw;
    protected boolean play;
    protected boolean active;

    private JTextArea infoTA;

    public AbstractBasePanel() {
        initComponents();
    }

    public void handleKeyEvent(KeyEvent e) {
        //implements only who need it
    }

    protected void logText(String text) {
        if (active && nonNull(infoTA)) {
            infoTA.setText(text);
        }
    }

    protected void fillRectElement(Graphics g, Element element) {
        fillRectElement(g, element.getColor(), element);
    }
    
    protected void fillRectElement(Graphics g, Color color, Element element) {
        g.setColor(color);
        g.fillRect(element.getX(), element.getY(), element.getWidth(), element.getHeight());
    }
    
    protected void drawRectElement(Graphics g, Element element) {
        g.setColor(element.getColor());
        g.drawRect(element.getX(), element.getY(), element.getWidth(), element.getHeight());
    }
    
    public void setDraw(boolean draw) {
        this.draw = draw;
        this.play = draw;
        
        if (!draw) {
            logText("");
        }
    }

    public void setPlay(boolean play) {
        this.play = play;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void setInfoTA(JTextArea infoTA) {
        this.infoTA = infoTA;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
