package project.lab6;

import java.awt.Component;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import project.lab6.cellautomat.CellPanel;
import project.lab6.crossroad.CrossroadPanel;

public class Application extends javax.swing.JFrame {

    private AbstractBasePanel selectedPanel;

    public Application() {
        initComponents();

        setSelectedPanel();
        addApplicationKeyEvent();
        addTabbedPanelChangeListener();
        
        addIntoTAToPanel(cellPanel);
        addIntoTAToPanel(crossroadPanel);
    }
    
    private void addApplicationKeyEvent() {
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
                .addKeyEventDispatcher((e) -> {
                    if (KeyEvent.KEY_PRESSED == e.getID()) {
                        selectedPanel.handleKeyEvent(e);
                    }
                    return false;
        });
    }

    private void addTabbedPanelChangeListener() {
        tabbedPanel.addChangeListener((e) -> setSelectedPanel());
    }

     private void addIntoTAToPanel(JPanel panel) {
        ((AbstractBasePanel) panel).setInfoTA(infoTA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startDrawButton = new javax.swing.JButton();
        endDrawButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        tabbedPanel = new javax.swing.JTabbedPane();
        cellPanel = new CellPanel();
        crossroadPanel = new CrossroadPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        startDrawButton.setText("Start draw");
        startDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDrawButtonActionPerformed(evt);
            }
        });

        endDrawButton.setText("End draw");
        endDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDrawButtonActionPerformed(evt);
            }
        });

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cellPanelLayout = new javax.swing.GroupLayout(cellPanel);
        cellPanel.setLayout(cellPanelLayout);
        cellPanelLayout.setHorizontalGroup(
            cellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cellPanelLayout.setVerticalGroup(
            cellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Cell automat", cellPanel);

        crossroadPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        crossroadPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        crossroadPanel.setSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout crossroadPanelLayout = new javax.swing.GroupLayout(crossroadPanel);
        crossroadPanel.setLayout(crossroadPanelLayout);
        crossroadPanelLayout.setHorizontalGroup(
            crossroadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        crossroadPanelLayout.setVerticalGroup(
            crossroadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Crossroads", crossroadPanel);

        infoTA.setColumns(1);
        infoTA.setRows(1);
        infoTA.setTabSize(10);
        infoTA.setAutoscrolls(false);
        infoTA.setFocusable(false);
        jScrollPane1.setViewportView(infoTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endDrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playButton)
                    .addComponent(stopButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startDrawButton)
                            .addComponent(playButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endDrawButton)
                            .addComponent(stopButton)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDrawButtonActionPerformed
        selectedPanel.setDraw(true);
    }//GEN-LAST:event_startDrawButtonActionPerformed

    private void endDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDrawButtonActionPerformed
        selectedPanel.setDraw(false);
    }//GEN-LAST:event_endDrawButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        selectedPanel.setPlay(true);
    }//GEN-LAST:event_playButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        selectedPanel.setPlay(false);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void setSelectedPanel() {
        for(Component component : tabbedPanel.getComponents()) {
            AbstractBasePanel panel = (AbstractBasePanel) component;
            panel.setDraw(false);
            panel.setActive(false);
        }
        
        infoTA.setText("");
        
        selectedPanel = (AbstractBasePanel) tabbedPanel.getSelectedComponent();
        selectedPanel.setActive(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cellPanel;
    private javax.swing.JPanel crossroadPanel;
    private javax.swing.JButton endDrawButton;
    private javax.swing.JTextArea infoTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton playButton;
    private javax.swing.JButton startDrawButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables
}
